In [1]:
from PIL import Image
import numpy as np
imgpil = Image.open("bateau.jpg")  
img = np.array(imgpil) # Transformation de l'image en tableau numpy
print(img[:10,:10])

[[[112 122 124]
  [112 120 123]
  [114 122 125]
  [118 123 127]
  [116 121 125]
  [118 121 126]
  [119 122 127]
  [122 123 128]
  [123 122 127]
  [124 124 126]]

 [[115 123 125]
  [114 122 125]
  [119 124 128]
  [118 123 127]
  [118 121 126]
  [118 121 126]
  [118 121 126]
  [126 129 134]
  [126 127 131]
  [128 128 130]]

 [[115 120 123]
  [113 118 122]
  [115 120 124]
  [117 122 126]
  [117 120 125]
  [119 122 127]
  [119 122 127]
  [118 123 127]
  [121 125 128]
  [126 127 129]]

 [[111 117 117]
  [115 120 123]
  [114 119 123]
  [113 121 124]
  [113 121 124]
  [117 122 126]
  [119 124 128]
  [118 122 125]
  [116 121 124]
  [118 122 125]]

 [[104 114 113]
  [105 113 115]
  [107 115 117]
  [105 115 117]
  [104 114 115]
  [108 116 118]
  [115 120 123]
  [118 122 125]
  [116 121 124]
  [117 122 125]]

 [[107 119 119]
  [108 118 119]
  [109 119 120]
  [116 126 127]
  [123 135 135]
  [122 132 133]
  [111 119 121]
  [110 118 120]
  [120 128 130]
  [125 133 136]]

 [[100 112 112]
  [ 95 107 1